language: go
env: BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
matrix:
  include:
  - go: 1.10.x
    script:
    - make vet
    - make test
  - go: 1.11.x
    env: GO111MODULE=on
    script:
    - make vet
    - make test
  - go: 1.11.x
    env:
    - GO111MODULE=off
    script:
    - make
    - OS=darwin make
    - OS=windows make
deploy:
  provider: releases
  api_key:
    secure: Inmh1DKOrv60DJUUcyqVIDn6mcG7qcrBs46dS0KlBlqJhZsuoAgWopDrZcMLx+X7kN784yP9/42J/IMeBjMaW5bk689cctOzRUaVP+dTmf8E/XbtpAirT8qwGwtmzVr2q9WfzL8Tg69UIa8Dbe0GB5H9Ru0cEAvjTKBVfbj7LyIpvIr1YseMY8N2EOJF6+68ZV3OWPQcQqpl9FFNq/13fKfTtgniQEO4h31fB/YjUAwQIXipSw1NbywBrHl2b/DGfd07rjL8ElohVXdLSNXC8SL2rvztgI86eNNeBhVGr8Q3trd2cFd2v/dFfg0BWAoe2wWff/jnQZbc9rx/bBA1CVN9VuI3uSCd8X+tkBZV+kJz4M8HVf2jWQ8pPu4q4fRkeaiYiCAkWnGinsVtzs0QpYzwZp/ZEnVBC+VbzfVZcDkTC0tRz1kzJeC36hkyged/s3m2PC/n5dww4O2OgTnWedhEe1D+wNGgqHXvwSBRBOK/jIhSuz1NBGdjK6srxdqOunMPXz8tYO30nIMs9JGx7VUkm9fC6oAYgNxsOlF24RGZnpH7/YOip1IR2ykUQR+Vbyng60r/sOVHT9Fcfm3+/oGJ0D1CJiaYYsQehgfyOK89vk63la3YyIqt4fCimN/Z0XFgvBSTlAR0pPLPp8qL0moIOE+GpYDlKHhfl0xAyiA=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: gini/dexter
    tags: true
branches:
  except:
  - "/^[0-9]/"
